
TITLE_LIST="uri_list"
APP_URL="request_joyce_metadata"
REQUEST_TITLE_EUHUBS='Title requesting in EuHubs4data platform'
TITLE_LIST_DESCP=""
TITLE_EU_DESC_JOB="Operations related to title requesting in EuHubs4data platform"
id="id"
name = 'name'
is_repo ='is_repo'
description ='description'
domains ='domains'
location ='location'
license ='license'
formats ='formats'
privacy ='privacy'
publisher ='publisher'
language ='language'
issued ='issued'
creator ='creator'
from_augmented_time ='augmented_time'
from_upload_time ='upload_time'
limit ='limit'    
url="url"
rdf_url='rdf_url'
landing_page='landing_page'
spatial='spatial'
similarity = 'similarity' 
source='source'
landing_page="landing_page"
team="team"
is_author="is_author"
modified="modified"

